import type { VehicleBrand } from "@/types/vehicle";

// Replace this catalog with a database or external vehicle API without changing the UI contract.
export const vehicleBrands: VehicleBrand[] = [
  ["Audi", "A3,A4,A5,A6,Q3,Q5,Q7,Q8"], ["BMW", "1 Serisi,2 Serisi,3 Serisi,5 Serisi,7 Serisi,X1,X3,X5,X6"], ["Mercedes-Benz", "A-Serisi,C-Serisi,E-Serisi,S-Serisi,GLA,GLC,GLE"], ["Volkswagen", "Golf,Passat,T-Roc,Tiguan,Transporter"], ["Toyota", "Corolla,Yaris,C-HR,RAV4,Camry,Land Cruiser"], ["Honda", "Civic,City,CR-V,HR-V"], ["Hyundai", "i10,i20,Elantra,Tucson,Santa Fe"], ["Kia", "Picanto,Rio,Ceed,Sportage,Sorento"], ["Renault", "Clio,Megane,Captur,Austral,Kadjar"], ["Peugeot", "208,308,408,2008,3008,5008"], ["Citroen", "C3,C4,C5 Aircross,Berlingo"], ["Fiat", "Egea,500,Panda,Tipo,Doblo"], ["Ford", "Fiesta,Focus,Puma,Kuga,Mustang,Ranger"], ["Opel", "Corsa,Astra,Mokka,Grandland"], ["Skoda", "Fabia,Scala,Octavia,Superb,Kamiq,Karoq,Kodiaq"], ["Seat", "Ibiza,Leon,Arona,Ateca"], ["Cupra", "Formentor,Born,Ateca,Leon"], ["Volvo", "S60,S90,XC40,XC60,XC90"], ["Nissan", "Micra,Juke,Qashqai,X-Trail"], ["Mazda", "Mazda2,Mazda3,CX-3,CX-5"], ["Mitsubishi", "Space Star,ASX,Eclipse Cross,L200"], ["Suzuki", "Swift,Vitara,S-Cross,Jimny"], ["Dacia", "Sandero,Duster,Jogger"], ["Tesla", "Model 3,Model Y,Model S,Model X"], ["Porsche", "Macan,Cayenne,Panamera,911,Taycan"], ["Land Rover", "Defender,Discovery,Discovery Sport"], ["Range Rover", "Evoque,Velar,Range Rover,Range Rover Sport"], ["Jeep", "Renegade,Compass,Wrangler,Grand Cherokee"], ["Alfa Romeo", "Giulia,Stelvio,Tonale"], ["Lexus", "UX,NX,RX,ES,LS"], ["Mini", "Cooper,Countryman,Clubman"], ["Jaguar", "XE, XF, E-Pace,F-Pace"], ["Subaru", "XV,Forester,Outback"], ["MG", "MG3,ZS,HS,Marvel R"], ["BYD", "Atto 3,Seal,Dolphin"], ["Chery", "Tiggo 7 Pro,Tiggo 8 Pro,Omoda 5"]
].map(([name, models]) => ({ name, slug: name.toLowerCase().replaceAll(" ", "-"), models: models.split(",") }));

export function getModelsForBrand(brand?: string): string[] {
  return vehicleBrands.find((item) => item.name === brand)?.models ?? [];
}
